"""empty message

Revision ID: 1af82be2c07a
Revises: e009e4658fba
Create Date: 2021-11-15 10:28:06.261020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1af82be2c07a'
down_revision = 'e009e4658fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=120), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('nick', sa.String(length=120), nullable=False))
    op.drop_column('user', 'task')
    op.drop_column('user', 'done')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('done', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('task', mysql.VARCHAR(length=120), nullable=False))
    op.drop_column('user', 'nick')
    op.drop_table('task')
    # ### end Alembic commands ###
