"""empty message

Revision ID: e009e4658fba
Revises: f383251a03b3
Create Date: 2021-11-13 19:26:13.020016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e009e4658fba'
down_revision = 'f383251a03b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('done', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'done')
    # ### end Alembic commands ###
